<a href="https://colab.research.google.com/github/Jayannthan/SSN-SEMESTER-5/blob/main/AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 1:

In [3]:
pip install binarytree

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.2 MB 9.4 MB/s 
     |████████████████████████████████| 42 kB 1.2 MB/s 
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
    Uninstalling setuptools-57.4.0:
      Successfully uninstalled setuptools-57.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
numba 0.56.2 requires setuptools<60, but you have setuptools 65.4.1 which is incompatible.


In [2]:
from binarytree import build
def generate(st,num):
    balls = []
    if(st=="red"):
        for i in range(num):
            balls.append(2*i+1)
    else:
        for i in range(1,num+1):
            balls.append(2*i)
    return balls


def dfs(balls,curr,siz,gs,state):
    if(curr<siz):
        print(balls[curr],end=" ")
        if(balls[curr]==gs):
            return 1
        if(state!=1):
            state=dfs(balls,2*curr+1,siz,gs,state)
            if(state==1):return 1
            state=dfs(balls,2*curr+2,siz,gs,state)
            if(state==1):return 1
        return state
        


def printchild(balls,curr,siz,gs):
    if(2*curr+1<siz):
        print(balls[2*curr+1],end=" ")
        if(balls[2*curr+1]==gs):return 1
    if(2*curr+2<siz):
        print(balls[2*curr+2],end=" ")
        if(balls[2*curr+2]==gs):return 1
    return 0

def bfs(balls,curr,siz,gs,state):
    if(curr<siz):
        state=printchild(balls,curr,siz,gs)
        if(state!=1):
            state=bfs(balls,2*curr+1,siz,gs,state)
        if(state!=1):
            state=bfs(balls,2*curr+2,siz,gs,state)
        return state
        
        


st=str(input("Enter String:"))
num=int(input("Enter number to generate number of balls:"))
print("You have chosen: "+ st)
print("No of balls to generate: " + str(num))

balls=generate(st,num)
print(balls)

root = build(balls)
print(root)


gs=int(input("Enter goal state of ball to traverse:"))
print("DFS TRACE:")
dfs(balls,0,num,gs,0)

print()
print("BFS TRACE:\n" + str(balls[0]),end=" ")
f=bfs(balls,0,num,gs,0)



Enter String:green
Enter number to generate number of balls:20
You have chosen: green
No of balls to generate: 20
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]

                      ____________2_________
                     /                      \
           _________4______              ____6___
          /                \            /        \
     ____8___              _10        _12        _14
    /        \            /   \      /   \      /   \
  _16        _18        _20    22   24    26   28    30
 /   \      /   \      /
32    34   36    38   40

Enter goal state of ball to traverse:24
DFS TRACE:
2 4 8 16 32 34 18 36 38 10 20 40 22 6 12 24 
BFS TRACE:
2 4 6 8 10 16 18 32 34 36 38 20 22 40 12 14 24 

In [ ]:
from anytree import build
import random
def generate(num,initial,final):
    randnos = []
    import random
    randnos=random.sample(range(initial,final+1), num)
    return randnos

def dls(cur_limit,limit,index,arr,N):
    if index >= len(arr):
        return False;
    if (limit+1) == cur_limit:
        cur_limit-=1
        return False;
    print(arr[index],end = " ")
    if arr[index]==N:
        return True
    cur_limit+=1
    if dls(cur_limit,limit,2*index+1,arr,N) == True:
        return True
    if dls(cur_limit,limit,2*index+2,arr,N) == True:
        return True
    return False   
from anytree import Node, RenderTree
def ids(limit,arr,N):
    for i in range(limit+1):
        print("level "+ (str)(i) +":",end = " ")
        nodes=dls(0,i,0,randnos,N)
        print()
        if(nodes==True): 
            print("\Found " + (str)(limit))
            return
    print("\nNot Found until Level " + (str)(limit))



num=int(input("Enter number to generate number of numbers:"))
intial=int(input("Enter initial number to generate:"))
final=int(input("Enter number to generate number of numbers:"))

randnos=generate(num,intial,final)
print(randnos)

root = build(randnos)
print(root)

N = int(input("Enter goal state : "))
limit = int(input("Enter limit : "))
nodes=dls(0,limit,0,randnos,N)
# if nodes==False : print("\nNot Found until Level " + (str)(limit))

print()
ids(limit,randnos,N)



Enter number to generate number of numbers:20
Enter initial number to generate:1
Enter number to generate number of numbers:100
[25, 71, 9, 97, 38, 35, 92, 29, 11, 99, 6, 24, 17, 59, 61, 74, 31, 42, 91, 19]

                       ____________25_________
                      /                       \
           __________71______              ____9___
          /                  \            /        \
     ____97___               _38        _35        _92
    /         \             /   \      /   \      /   \
  _29         _11         _99    6    24    17   59    61
 /   \       /   \       /
74    31    42    91    19

Enter goal state : 74
Enter limit : 4
25 71 97 29 74 
level 0: 25 
level 1: 25 71 9 
level 2: 25 71 97 38 9 35 92 
level 3: 25 71 97 29 11 38 99 6 9 35 24 17 92 59 61 
level 4: 25 71 97 29 74 
\Found 4


In [ ]:
pathcostbfs=0
pathcostdfs=0 
pathcostdls=0

def next_state(a, b):
  nodes = []
  if (a != 0):
    nodes.append((0, b))
    if (a <= 3 - b):
      nodes.append((0, b + a))
    else:
      nodes.append((a - (3 - b), 3))
  if (b != 0):
    nodes.append((a, 0))
    if (b <= 4 - a):
      nodes.append((a + b, 0))
    else:
      nodes.append((4, 3 - (4 - a)))
  if (a != 4):
    nodes.append((4, b))
  if (b != 3):
    nodes.append((a, 3))
  return nodes


def bfs():
  visited = set()
  que.append(((0, 0), 0))
  while len(que) > 0:
    current_state, level = que.pop(0)
    if current_state not in visited:
      visited.add(current_state)
      pathcostbfs=pathcostbfs+1;
      print(current_state,end=" ")
      if current_state in goal_states:
        print("Goal state reached")
        break
    nxt = next_state(*current_state)
    for x in nxt:
        que.append((x, level + 1))

def dfs():
  visited = set()
  sta.append(((0, 0), 0))
  while len(sta) > 0:
    current_state, level = sta.pop(len(sta)-1)
    if current_state not in visited:
      visited.add(current_state)
      pathcostdfs=pathcostdfs+1
      print(current_state,end=" ")
      nxt = next_state(*current_state)
      for x in nxt:
        sta.append((x, level + 1))
      if current_state in goal_states:
        print("Goal state reached")
        break

def dls(limit):
  visited = set()
  sta=[]
  sta.append(((0, 0), 0))
  while len(sta) > 0:
    current_state, level = sta.pop(len(sta)-1)
    if current_state not in visited:
      visited.add(current_state)
      pathcostdls=pathcostdls+1
      print(current_state,end=" ")
      if current_state in goal_states:
        print("Goal state reached")
        return 1
      if level != limit:
        nxt = next_state(*current_state)
        for x in nxt:
            sta.append((x, level + 1))


def ids():
    limit=0
    while(limit+1):
        flag=dls(limit)
        if(flag==1):
            break
        limit=limit+1
        print()

# print(1)
initial_state = (0, 0)
goal_states = [(2, 0), (2, 1), (2, 2), (2, 3)]
que = []
sta = []
# temp=[]
# temp1=[]
limit = 6
print("BFS")
bfs()
print("bfspathcost =",pathcostbfs )
print("DFS")
dfs()
print("dfspathcost =",pathcostdfs )
print("DLS")
limit = int(input("Enter limit : "))
a=dls(limit)
print("dlspathcost =",pathcostdls )
print("IDS")
ids()

SyntaxError: ignored

In [ ]:
def next_state(a, b):
  nodes = []
  if (a != 0):
    nodes.append((0, b))
    if (a <= 3 - b):
      nodes.append((0, b + a))
    else:
      nodes.append((a - (3 - b), 3))
  if (b != 0):
    nodes.append((a, 0))
    if (b <= 4 - a):
      nodes.append((a + b, 0))
    else:
      nodes.append((4, 3 - (4 - a)))
  if (a != 4):
    nodes.append((4, b))
  if (b != 3):
    nodes.append((a, 3))
  return nodes

def bfs():
  global bfspath
  visited = set()
  que.append(((0, 0), 0))
  while len(que) > 0:
    current_state, level = que.pop(0)
    if current_state not in visited:
      bfspath=bfspath+1
      visited.add(current_state)
      print(current_state,end=" ")
      if current_state in goal_states:
        print("Goal state reached")
        break
    nxt = next_state(*current_state)
    for x in nxt:
        que.append((x, level + 1))

          
def dfs():
  global dfspath
  visited = set()
  sta.append(((0, 0), 0))
  while len(sta) > 0:
    current_state, level = sta.pop(len(sta)-1)
    if current_state not in visited:
      dfspath=dfspath+1
      visited.add(current_state)
      print(current_state,end=" ")
      nxt = next_state(*current_state)
      for x in nxt:
        sta.append((x, level + 1))
      if current_state in goal_states:
        print("Goal state reached")
        break

def dls(limit):
  global dlspath
  visited = set()
  sta=[]
  sta.append(((0, 0), 0))
  while len(sta) > 0:
    current_state, level = sta.pop(len(sta)-1)
    if current_state not in visited:
      dlspath=dlspath+1
      visited.add(current_state)
      print(current_state,end=" ")
      if current_state in goal_states:
        print("Goal state reached")
        return 1
      if level != limit:
        nxt = next_state(*current_state)
        for x in nxt:
            sta.append((x, level + 1))


def ids():
    limit=0
    while(limit+1):
        flag=dls(limit)
        if(flag==1):
            break
        limit=limit+1
        print()

initial_state = (0, 0)
goal_states = [(2, 0), (2, 1), (2, 2), (2, 3)]
que = []
sta = []
bfspath=0
dfspath=0
dlspath=0
limit = 6
print("BFS")
bfs()
print()
print("BFS path cost: ",bfspath)
print()
print("DFS")
dfs()
print()
print("DFS path cost: ",dfspath)
print()
print("DLS")
a=dls(6)
print()
dlspathcost=dlspath
print()
dlspath=0
print("IDS")
ids()
print()
idspathcost=dlspath
arr=[("BFS",bfspath),("DFS",dfspath),("DLS",dlspathcost),("IDS",idspathcost)]
arr.sort(key=lambda x: x[1])
print(arr[0][0],"is the best solution as it has the shortest path cost of",arr[0][1])

BFS
(0, 0) (4, 0) (0, 3) (1, 3) (4, 3) (3, 0) (1, 0) (3, 3) (0, 1) (4, 2) (4, 1) (0, 2) (2, 3) Goal state reached

BFS path cost:  13

DFS
(0, 0) (0, 3) (4, 3) (4, 0) (1, 3) (1, 0) (0, 1) (4, 1) (2, 3) Goal state reached

DFS path cost:  9

DLS
(0, 0) (0, 3) (4, 3) (4, 0) (1, 3) (1, 0) (0, 1) (3, 0) (3, 3) (4, 2) (0, 2) (2, 0) Goal state reached


IDS
(0, 0) 
(0, 0) (0, 3) (4, 0) 
(0, 0) (0, 3) (4, 3) (3, 0) (4, 0) (1, 3) 
(0, 0) (0, 3) (4, 3) (4, 0) (3, 0) (3, 3) 
(0, 0) (0, 3) (4, 3) (4, 0) (1, 3) (3, 0) (3, 3) (4, 2) 
(0, 0) (0, 3) (4, 3) (4, 0) (1, 3) (1, 0) (3, 0) (3, 3) (4, 2) (0, 2) 
(0, 0) (0, 3) (4, 3) (4, 0) (1, 3) (1, 0) (0, 1) (3, 0) (3, 3) (4, 2) (0, 2) (2, 0) Goal state reached

DFS is the best solution as it has the shortest path cost of 9


In [ ]:
import math

def printHeuristic(hr):
  ch = 'A'
  for i in range(len(graph)):
    print(chr(ord(ch) + i), end="\t")
  print()
  for i in range(len(hr)):
      print(hr[i],end="\t")

def printGraph(graph):
    print("\t", end="")
    ch = 'A'
    for i in range(len(graph)):
      print(chr(ord(ch) + i), end="\t")
    print()
    for i in range(len(graph)):
      for j in range(len(graph[0])):
        if(j==0 and i==0):
          print("A",end="\t")
        if(j==0 and i==len(graph)-1):
          print("H",end="\t")
        if (j == 0 and i!=0 and i!=len(graph)-1):
            print(chr(ord(ch) + i-1), end="\t")
        print(graph[i][j], end="\t")
      print()

def minDistance(dist,visited,n):
  min=math.inf
  for v in range(n):
    if dist[v] < min and visited[v] == False:
      min = dist[v]
      min_index = v
 
  return min_index

def dijkstra(graph,n,hr):
  dist=[]
  dist1=[]
  visited=[]
  path=[]
  for i in range(n):
    dist.append(math.inf)
    dist1.append(math.inf)
    visited.append(False)
    path.append([])
  start=0
  dist[start]=0
  dist1[start]=0
  path[0].append(0)
  for j in range(n):
    u = minDistance(dist, visited,n)
    visited[u] = True
    for v in range(n):
      if (graph[u][v] > 0 and visited[v] == False and dist[v] > dist[u] +hr[v]):
        dist1[v]=dist1[u] + graph[u][v]
        dist[v] = dist[u] +hr[v]
        for i in range(len(path[v])):
            path[v].pop()
        for i in range(len(path[u])):
            path[v].append(path[u][i])
        path[v].append(v)
  return dist1[n-1],path[n-1]

def astar(graph,n,hr):
  dist=[]
  dist1=[]
  visited=[]
  path=[]
  for i in range(n):
    dist.append(math.inf)
    dist1.append(math.inf)
    visited.append(False)
    path.append([])
  start=0
  dist[start]=0
  dist1[start]=0
  path[0].append(0)
  for j in range(n):
    u = minDistance(dist, visited,n)
    visited[u] = True
    for v in range(n):
      if (graph[u][v] > 0 and visited[v] == False and dist[v] > dist[u] + graph[u][v]+hr[v]):
        dist1[v]=dist1[u] + graph[u][v]
        dist[v] = dist[u] + graph[u][v]+hr[v]
        for i in range(len(path[v])):
            path[v].pop()
        for i in range(len(path[u])):
            path[v].append(path[u][i])
        path[v].append(v)
  return dist1[n-1],path[n-1]
   
# Main Program

graph = [
    [0,9,6,0,0,0,0,0],
    [9,0,0,5,0,0,0,0],
    [6,0,0,8,0,5,0,0],
    [0,5,8,0,7,0,6,0],
    [0,0,0,7,0,0,0,4],
    [0,0,5,0,0,0,7,0],
    [0,0,0,6,0,7,0,8],
    [0,0,0,0,4,0,8,0],
]
hr=[4,3,3,2,1,2,1,0]

n=8
while (True):
  print()
  ch = int(input("Enter choice(1-Print graph, 2-A* search, 3-Greedy):"))
  if (ch == 1):
    print("Graph-")
    print()
    printGraph(graph)
    print()
    print("Heuristic Value-")
    print()
    printHeuristic(hr)
    print()
    print()
  elif(ch==2):
    print("A*")
    v,p=astar(graph,8,hr)
    print("Value = "+ str(v) )
    print("PATH:-")
    ch='A'
    for i in range(len(p)):
      print(chr(ord(ch) + p[i]),end="")
      print(" --> ",end="")
  elif (ch == 3):
    print("Greedy")
    v,p=dijkstra(graph,8,hr)
    print("Value = "+ str(v) )
    print("PATH:-")
    ch='A'
    for i in range(len(p)):
      print(chr(ord(ch) + p[i]),end="")
      print(" --> ",end="")
  else:
      break



A*
Value = 25
PATH:-
A --> C --> D --> E --> H --> 
Greedy
Value = 25
PATH:-
A --> B --> D --> E --> H --> 


In [ ]:
# pip install numpy

import numpy as np
import random



def geneticalgo(nq,maxFitness):
	population = np.random.randint(nq, size=(8, 8))
	print("population:",population)


nq = int(input("Enter Number of Queens: ")) #say N = 8
maxFitness = (nq*(nq-1))/2  # 8*7/2 = 28
geneticalgo(nq,maxFitness)

Enter Number of Queens: 8
population: [[5 0 0 7 2 1 5 2]
 [4 5 4 7 3 4 1 6]
 [2 1 5 6 6 5 2 6]
 [4 7 5 3 6 1 5 3]
 [2 2 4 1 7 1 4 2]
 [0 6 6 0 6 6 3 5]
 [2 1 5 2 6 0 3 3]
 [6 6 7 5 4 0 0 5]]


In [8]:
import random
def fitnessFunction(state):
  fitness = 0
  for i in range(0, 7 + 1):
    for j in range(i + 1, 7 + 1):
      if (state[i] != state[j] and j - i != abs(state[i] - state[j])):
        fitness += 1
  return fitness

def createChildren(parent1, parent2):
    state1 = parent1[2]
    state2 = parent2[2]
    parent1[1] -= 1
    parent2[1] -= 1
    #crossover
    child1 = [state1[0], state1[1], state1[2], state1[3],
             state2[4], state2[5], state2[6], state2[7]]
    child2 = [state2[0], state2[1], state2[2], state2[3],
             state1[4], state1[5], state1[6], state1[7]]
    #mutation
    pos = random.randint(0, 7)
    val = random.randint(0, 7)
    child1[pos] = val
    pos = random.randint(0, 7)
    val = random.randint(0, 7)
    child2[pos] = val
    return [fitnessFunction(child1), 0, child1], [fitnessFunction(child2), 0, child2]

def GA(states):
    loops=0
    while (states[0][0] < 28):
        loops += 1
        print("Loop : ", loops,"\tMaximum obtained fitness till now: ",states[0][0])

        for i in range(0, min(2, len(states) - 1), 2):
            parent1 = states[i]
            parent2 = states[i + 1]
            children1,children2 = createChildren(parent1, parent2)
        states.append(children1)
        states.append(children2)
        states.sort(reverse = True)
    print("\n\n!!!FOUND THE ANSWER!!!\nLoop : ", loops+1,"\tMaximum fitness: ",states[0][0])
    return states



K = 10
states = []
for i in range(K):
	state = [random.randint(0, 7) for j in range(8)]
	print(state)
	states.append([fitnessFunction(state), 0, state])
states.sort(reverse = True)
states=GA(states)
print("Solution : ", states[0][2])
# print(states)

[2, 3, 2, 0, 4, 0, 1, 2]
[5, 2, 3, 0, 1, 0, 2, 7]
[4, 7, 0, 4, 3, 3, 2, 6]
[4, 5, 5, 4, 1, 7, 3, 3]
[1, 4, 0, 5, 6, 0, 0, 0]
[4, 5, 4, 3, 6, 1, 7, 1]
[0, 1, 5, 3, 5, 1, 1, 1]
[6, 6, 7, 0, 7, 0, 7, 6]
[4, 0, 1, 5, 2, 6, 4, 6]
[3, 2, 3, 7, 0, 5, 4, 0]
Loop :  1 	Maximum obtained fitness till now:  22
Loop :  2 	Maximum obtained fitness till now:  23
Loop :  3 	Maximum obtained fitness till now:  24
Loop :  4 	Maximum obtained fitness till now:  24
Loop :  5 	Maximum obtained fitness till now:  24
Loop :  6 	Maximum obtained fitness till now:  24
Loop :  7 	Maximum obtained fitness till now:  24
Loop :  8 	Maximum obtained fitness till now:  24
Loop :  9 	Maximum obtained fitness till now:  24
Loop :  10 	Maximum obtained fitness till now:  24
Loop :  11 	Maximum obtained fitness till now:  24
Loop :  12 	Maximum obtained fitness till now:  24
Loop :  13 	Maximum obtained fitness till now:  24
Loop :  14 	Maximum obtained fitness till now:  24
Loop :  15 	Maximum obtained fitness till now

AI 6:Minmax Algorithm

In [18]:
from binarytree import build

def generate(limit):
    values=[]
    for i in range(1,2**(limit+1)):
        values.append(i)
    print(values)
    return values


def successors(node):
  return 2 * node, 2 * node + 1

def evaluate(node):
  return node


def maxplayer(node,level,limit):
    ans = 0
    for nextNode in successors(node):
      ans = max(ans, minimax(nextNode, 'min', level + 1, limit))
    values[node - 1] = str([node, ans])
    return ans

def minplayer(node,level,limit):
    ans = 10000 
    for nextNode in successors(node):
      ans = min(ans, minimax(nextNode, 'max', level + 1, limit))
    values[node - 1] = str([node, ans])
    return ans

def minimax(node, player, level, limit):
  if level == limit:
    ans = evaluate(node)
    values[node - 1] = str([node, ans])
    return ans
   
  if player == 'max':
    return maxplayer(node,level,limit)
  else:
    return minplayer(node,level,limit)
   


limit = int(input('Enter limit : '))
print("Building Tree")

values = generate(limit)
print(values)
root = build(values)
print(root)

print('Answer : ', minimax(1, 'max', 0, limit))



Enter limit : 3
Building Tree
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

        ________1________
       /                 \
    __2___             ___3___
   /      \           /       \
  4       _5        _6        _7
 / \     /  \      /  \      /  \
8   9   10   11   12   13   14   15

Answer :  13
